packages:
  - apps/*
  - packages/public/*
  - packages/internal/*
  - tooling/*

onlyBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver

catalogs:
  react:
    react: 19.2.1
    react-dom: 19.2.1
    "@types/react": 19.2.1
    "@types/react-dom": 19.2.1
  drizzle:
    drizzle-orm: 1.0.0-beta.2-86f844e
    drizzle-kit: 1.0.0-beta.2-86f844e
  better-auth:
    better-auth: 1.4.5
  orpc:
    "@orpc/arktype": 1.12.2
    "@orpc/client": 1.12.2
    "@orpc/contract": 1.12.2
    "@orpc/openapi": 1.12.2
    "@orpc/server": 1.12.2
    "@orpc/tanstack-query": 1.12.2
    "@orpc/zod": 1.12.2
